import type { IConstructTask } from "@/types/construct-task";

export const taskConstants: IConstructTask[] = [
  {
    id: "1",
    name: "Foundation Work",
    description: "Excavate and pour concrete for the building foundation.",
    status: "pending",
    iconID: "lampwork",
    coordinates: { x: 100, y: 200 },
    createdAt: "2024-06-01T08:00:00Z",
    updatedAt: "2024-06-01T08:00:00Z",
    checklist: [
      {
        id: "1",
        name: "Excavate and pour concrete for the building foundation.",
        status: { id: "pending", name: "Pending" },
        iconID: "lampwork",
        description: "Excavate and pour concrete for the building foundation.",
      },
      {
        id: "2",
        name: "Install reinforcement steel",
        status: { id: "completed", name: "Completed" },
        iconID: "lampwork",
        description: "Install reinforcement steel",
      },
    ],
  },
  {
    id: "2",
    name: "Framing",
    description: "Construct the structural framework for walls and floors.",
    status: "awaiting",
    iconID: "lighting",
    coordinates: { x: 300, y: 250 },
    createdAt: "2024-06-01T08:10:00Z",
    updatedAt: "2024-06-01T08:10:00Z",
    checklist: [
      {
        id: "1",
        name: "Excavate and pour concrete for the building foundation.",
        status: { id: "pending", name: "Pending" },
        iconID: "lampwork",
        description: "Excavate and pour concrete for the building foundation.",
      },
      {
        id: "2",
        name: "Install reinforcement steel",
        status: { id: "completed", name: "Completed" },
        iconID: "lampwork",
        description: "Install reinforcement steel",
      },
    ],
  },
  {
    id: "3",
    name: "Roof Installation",
    description: "Install trusses and roofing materials.",
    status: "in-progress",
    iconID: "electrical",
    coordinates: { x: 500, y: 180 },
    createdAt: "2024-06-01T08:20:00Z",
    updatedAt: "2024-06-01T08:20:00Z",
    checklist: [
      {
        id: "1",
        name: "Excavate and pour concrete for the building foundation.",
        status: { id: "pending", name: "Pending" },
        iconID: "lampwork",
        description: "Excavate and pour concrete for the building foundation.",
      },
    ],
  },
  {
    id: "4",
    name: "Electrical Wiring",
    description: "Run electrical wiring and install panels/outlets.",
    status: "completed",
    iconID: "plumbing",
    coordinates: { x: 200, y: 400 },
    createdAt: "2024-06-01T08:30:00Z",
    updatedAt: "2024-06-01T08:30:00Z",
    checklist: [
      {
        id: "1",
        name: "Excavate and pour concrete for the building foundation.",
        status: { id: "pending", name: "Pending" },
        iconID: "lampwork",
        description: "Excavate and pour concrete for the building foundation.",
      },
    ],
  },
  {
    id: "5",
    name: "Interior Finishing",
    description: "Install drywall, paint, and complete interior finishes.",
    status: "pending",
    iconID: "painting",
    coordinates: { x: 350, y: 350 },
    createdAt: "2024-06-01T08:40:00Z",
    updatedAt: "2024-06-01T08:40:00Z",
    checklist: [
      {
        id: "1",
        name: "Excavate and pour concrete for the building foundation.",
        status: { id: "pending", name: "Pending" },
        iconID: "lampwork",
        description: "Excavate and pour concrete for the building foundation.",
      },
    ],
  },
];
